### ISSUE TITLE
hello world! example 

### ISSUE THREAD

**Issue by unnir** [Lucretiel/genetics#4]
I have these error messages for the hello world example. 

```
Traceback (most recent call last):
  File "/genetics-master/hello_world.py", line 42, in <module>
    best, best_score, average_score = dna_stats(population)
  File "/genetics-master/hello_world.py", line 32, in dna_stats
    best_dna = max(population)
TypeError: unorderable types: WordDNA() > WordDNA()
```

**Comment by EmbolismSoil** [comment]
you should provide the method '\_\_gt\_\_' so that the 'max' function can choice an greater instance of WordDNA  when running:

```python
class WordDNA(genetics.arrayed_segment(len(solution), LetterComponent)):
    def score(self):
        return sum(comp.value == letter for comp, letter in zip(self, solution))

    def __str__(self):
        return ''.join(comp.value for comp in self)

    def __gt__(self, other):
        return self.score() > other.score()
```

**Comment by EmbolismSoil** [comment]
class WordDNA(genetics.arrayed_segment(len(solution), LetterComponent)):
    def score(self):
        return sum(comp.value == letter for comp, letter in zip(self, solution))

    def __str__(self):
        return ''.join(comp.value for comp in self)

    def __gt__(self, other):
        return self.score() > other.score()
